"""initial migration

Revision ID: 519371c280f3
Revises: 365178076274
Create Date: 2018-02-13 14:21:38.533183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519371c280f3'
down_revision = '365178076274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
