"""initial migration

Revision ID: a59299e78fe4
Revises: cea1a11b3ce2
Create Date: 2018-02-14 11:29:02.645839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59299e78fe4'
down_revision = 'cea1a11b3ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('hh', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'hh')
    # ### end Alembic commands ###
