"""initial migration

Revision ID: ddcd69b54c9e
Revises: c317542ac48d
Create Date: 2018-02-14 21:34:25.747694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddcd69b54c9e'
down_revision = 'c317542ac48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'version_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
