"""initial migration

Revision ID: 496e65afb59e
Revises: a59299e78fe4
Create Date: 2018-02-14 11:29:47.318548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '496e65afb59e'
down_revision = 'a59299e78fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'hh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('hh', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
